# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f768360d446dfd5cc8c80a2a84e3378d29d5dac0ff039365d0a536fa17010f1940b08cc56b83911f93617bdf0cb7f48ed253055cff91e9c3eb686b391edcb226

test:
  secret_key_base: 24d85c23b3934b8acac596b94b19bbd5d26dc40e7ec406b03a8848d70839c5874a7cfb275e1d6d51fcf730453bde4c59b256b8e160b772d386899c11b7a999b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
